# Generated by Django 4.2.4 on 2023-09-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApplyModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagem_input",
                    models.ImageField(
                        blank=True, editable=False, null=True, upload_to=""
                    ),
                ),
                (
                    "datahora",
                    models.IntegerField(blank=True, editable=False, null=True),
                ),
                (
                    "detect_class",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "conf_class",
                    models.CharField(
                        blank=True, editable=False, max_length=10, null=True
                    ),
                ),
                (
                    "principal_cor",
                    models.CharField(
                        blank=True, editable=False, max_length=50, null=True
                    ),
                ),
                (
                    "principal_cor_conf",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "conf_claro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "conf_escuro",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "conf_padrao",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        editable=False,
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "imagem_output",
                    models.ImageField(
                        blank=True, editable=False, null=True, upload_to=""
                    ),
                ),
            ],
        ),
    ]
